stepper_1_gear_ratio: 4.75
stepper_2_gear_ratio: 7.33333333
stepper_3_gear_ratio: 7
stepper_4_gear_ratio: 1
stepper_1_offset_position: 1.65457
stepper_2_offset_position: 0.5236
stepper_3_offset_position: -0.3142
stepper_4_offset_position: 2.13454
stepper_1_home_position: 0
stepper_2_home_position: 0.5236
stepper_3_home_position: -0.3142
stepper_4_home_position: 0
stepper_1_direction: -1
stepper_2_direction: -1
stepper_3_direction: 1
stepper_4_direction: -1
stepper_1_max_effort: 2000
stepper_2_max_effort: 2234
stepper_3_max_effort: 2792
stepper_4_max_effort: 2000
