#
#
# Processes to launch from gauss_rpi node
# (don't put circular dependencies)
#

# processes:
#     - name: 'gazebo'
#       launch_on_startup: true
#       delay_before_start: 0.0
#       cmd: 'roslaunch gauss_gazebo gauss_gazebo.launch'
#       args: 
#           []
#       dependencies:
#           []
#     - name: 'robot_commander'
#       launch_on_startup: true
#       delay_before_start: 4.0 # Additional delay for Moveit to load controllers
#       cmd: 'roslaunch gauss_bringup robot_commander.launch'
#       args: 
#           []
#       dependencies:
#           - gazebo
#     - name: 'user_interface'
#       launch_on_startup: true
#       delay_before_start: 0.0
#       cmd: 'roslaunch gauss_bringup user_interface.launch'
#       args: 
#         []
#       dependencies:
#           - gazebo
#           - robot_commander


processes:    
    - name: 'robot_commander'
      launch_on_startup: true
      delay_before_start: 4.0 # Additional delay for Moveit to load controllers
      cmd: 'roslaunch gauss_bringup robot_commander_simulator.launch'
      args: 
          []
      dependencies:
          []
    - name: 'user_interface'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch gauss_bringup user_interface.launch'
      args: 
        []
      dependencies:
          - robot_commander
         